# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty

# Setup
title:            Hamish Willee @ Community
copyright: © 2014 Jenosam Pty Ltd. All Rights Reserved.

url:              http://annhan.github.io
paginate:         1
baseurl:          
author:
  name:           An Nhàn
  url:            https://twitter.com/annhandt09
  email:          annhandt09@gmail.com
username: hamishwillee
description: "Blog discussing, online Community management, developers, developer tools, jekyll and API documentation."
bugreports: https://github.com/hamishwillee/hamishwillee.github.io/issues/new


# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/hamishwillee/hamishwillee.github.io



pages_list:       
  About: '/about/'
  Blogs: '/blog/'
  Twitter: 'http://twitter.com/hamishwillee'
  Feed: '/rss.xml'


# Site settings - to be integrated



beer: relatedpostsdisabled, but could perhaps do something with tags.

# Deprecated
# tagline:          ""


sass:
    sass_dir: /source/assets/bower_components/bootstrap-sass-official/assets/stylesheets


